force-app/main/default/objects/Assets__c/Assets__c.object-meta.xml
<CustomObject>
    <label>資産</label>
    <nameField>
        <label>資産名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryResults__c/InventoryResults__c.object-meta.xml
<CustomObject>
    <label>棚卸結果</label>
    <nameField>
        <displayFormat>IR-{YYYY}{MM}-{0000}</displayFormat>
        <label>棚卸結果No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryResults__c/fields/Assets__c.field-meta.xml
<CustomField>
    <fullName>Assets__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>資産</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Assets__c.InventoryTarget__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Assets__c</referenceTo>
    <relationshipLabel>棚卸結果</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestInventory_Trg.cls
/* @Contents 資産管理
 * @Author matsuzaki
 * @Since 2020/09/08
 * @LastUpdate 2020/09/08
 */
@isTest(SeeAllData=false)
public class TestInventory_Trg {
    @isTest static void Test_Inventory_Trg() {
        TestCreateDataUtil CreateDataUtil = new TestCreateDataUtil();

        //テスト開始
        Test.starttest();
        User adminUser = CreateDataUtil.createdUser('CreateAssetsRecordadmin','admin');

        System.runAs(adminUser){
            String recordNameAdmin = 'admin';
            List<Assets__c> AssetsList = CreateDataUtil.createAssetsRecord(recordNameAdmin);
        }

        User standardUser = CreateDataUtil.createdUser('TestInventory_Trg', '');
        CreateDataUtil.getPermissionSet(standardUser, 'AssetsManagementPermset');

        System.runAs (standardUser) {
            String recordNameStandard = 'Standard';
            List<InventoryResults__c> newInventoryResultList = CreateDataUtil.createInventoryRecord(recordNameStandard);
        }
        Test.stoptest();
    }

}