force-app/main/default/objects/Assets__c/Assets__c.object-meta.xml
<CustomObject>
    <label>資産</label>
    <nameField>
        <label>資産名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assets__c/fields/InventoryTarget__c.field-meta.xml
<CustomField>
    <fullName>InventoryTarget__c</fullName>
    <defaultValue>true</defaultValue>
    <label>棚卸対象</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assets__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>使用者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AssetUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>棚卸</label>
    <nameField>
        <displayFormat>I-{YYYY}{MM}-{0000}</displayFormat>
        <label>棚卸No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryResults__c/InventoryResults__c.object-meta.xml
<CustomObject>
    <label>棚卸結果</label>
    <nameField>
        <displayFormat>IR-{YYYY}{MM}-{0000}</displayFormat>
        <label>棚卸結果No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryResults__c/fields/Assets__c.field-meta.xml
<CustomField>
    <fullName>Assets__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>資産</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Assets__c.InventoryTarget__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Assets__c</referenceTo>
    <relationshipLabel>棚卸結果</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryResults__c/fields/InventoryYear__c.field-meta.xml
<CustomField>
    <fullName>InventoryYear__c</fullName>
    <label>棚卸年度</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>棚卸結果</relationshipLabel>
    <relationshipName>InventoryYear</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InventoryResults__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>使用者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResultUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InventoryTriggerHandler.cls
/* @Contents 資産管理
 * @Author matsuzaki
 * @Since 2020/09/07
 * @LastUpdate 2020/09/07
 */
public with sharing class InventoryTriggerHandler {

    public static boolean hasExecuted = false;
    private boolean m_isExrcuting = false;
    private integer BatchSize = 0;

    public InventoryTriggerHandler(boolean isExcuting, integer size) {
        m_isExrcuting = isExcuting;
        BatchSize = size;
    }

    public List<Inventory__c> OnAfterInsert(List<Inventory__c> newInventory){
        
        //棚卸対象の資産を全件取得
        List<Assets__c> AssetsList = [SELECT id , User__c FROM Assets__c WHERE InventoryTarget__c = true];
        List<InventoryResults__C> InvResultList = new List<InventoryResults__C>();
    
        //棚卸対象の資産件数分、棚卸結果を作成
        for(Integer i = 0 ; i < AssetsList.size() ; i++){
            InventoryResults__C IR = new InventoryResults__C(InventoryYear__c = newInventory[0].id,
                                                            Assets__c = AssetsList[i].id,
                                                            User__c = AssetsList[i].User__c);
            InvResultList.add(IR);
        }

        try{
            System.debug('Attempting to insert positions');
            insert InvResultList;
            System.debug('Insert complete');
        }catch(System.DmlException e){
            System.debug('DML exception:' + e.getDmlMessage(0));
        }
    
    return newInventory;
    }
}