force-app/main/default/objects/Assets__c/Assets__c.object-meta.xml
<CustomObject>
    <label>資産</label>
    <nameField>
        <label>資産名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assets__c/fields/BarcodeNumber__c.field-meta.xml
<CustomField>
    <fullName>BarcodeNumber__c</fullName>
    <label>バーコード番号</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InventoryResults__c/InventoryResults__c.object-meta.xml
<CustomObject>
    <label>棚卸結果</label>
    <nameField>
        <displayFormat>IR-{YYYY}{MM}-{0000}</displayFormat>
        <label>棚卸結果No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryResults__c/fields/Assets__c.field-meta.xml
<CustomField>
    <fullName>Assets__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>資産</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Assets__c.InventoryTarget__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Assets__c</referenceTo>
    <relationshipLabel>棚卸結果</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryResults__c/fields/BarcodeNumber__c.field-meta.xml
<CustomField>
    <fullName>BarcodeNumber__c</fullName>
    <formula>Assets__r.BarcodeNumber__c</formula>
    <label>バーコード番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/inventMobileApplicationControler.cls
public with sharing class inventMobileApplicationControler {
    @AuraEnabled(Cacheable=true)
    public static List<Assets__c> searchAssets(String BarcodeNumber) {
        if(BarcodeNumber != null) {
            Decimal decBarcodeNumber = Decimal.valueOf(BarcodeNumber);
            return [SELECT Id FROM Assets__c WHERE BarcodeNumber__c = :decBarcodeNumber LIMIT 1];
        } else {
            return null;
        }
    }

    @AuraEnabled(Cacheable=true)
    public static List<InventoryResults__c> searchInventoryResults(String BarcodeNumber) {
        if(BarcodeNumber != null) {
            Decimal decBarcodeNumber = Decimal.valueOf(BarcodeNumber);
            return [SELECT Id FROM InventoryResults__c WHERE BarcodeNumber__c = :decBarcodeNumber LIMIT 1];
        } else {
            return null;
        }
    }
}